stages {
        stage("Terraform plan") {
            steps {
                sh "terraform plan"
            }
        }

        stage("Terraform apply") {
            steps {
                sh "terraform apply"
            }
        }
}