
pipeline {
   agent any
        stages {

                stage("Terraform init") {
                        steps {
                            sh "cd \"Lab 3\""
                            sh "terraform init"
                        }
                    }

                stage("Terraform plan") {
                    steps {
                        sh "terraform plan"
                    }
                }

                stage("Terraform apply") {
                    steps {
                        sh "terraform apply"
                    }
                }
        }
}